source 'http://rubygems.org'

gem 'sinatra', require: 'sinatra/base'
gem 'pg'
gem 'rake'
gem 'puma'
gem 'slim'
gem 'faraday'
gem 'fast_jsonapi'
gem 'pry'
gem 'json'
gem 'dotenv'
gem 'require_all'
 
group :development, :test do
  gem 'factory_bot'
  gem 'faker'
  gem 'rspec'
  gem 'capybara'
  gem 'rack-test'
  gem 'launchy'
  gem 'shoulda-matchers'
  gem 'simplecov'
  gem 'webmock'
  gem 'vcr'
end
