source 'http://rubygems.org'

gem 'sinatra', require: 'sinatra/base'
gem 'pg'
gem 'rake'
gem 'puma'
gem 'slim'
gem 'faraday'
gem 'fast_jsonapi'
gem 'pry'
gem 'json'
gem 'dotenv'
gem 'require_all'
gem 'rack-test'
gem 'launchy'
gem 'selenium-webdriver'

group :test, :development do
  gem 'simplecov'
  gem 'webmock'
  gem 'vcr'
  gem 'shoulda-matchers'
  gem 'factory_bot'
  gem 'faker'
  gem 'rspec'
  gem 'capybara'
end
